services:
  app:
    container_name: nginx
    image: public.ecr.aws/nginx/nginx:stable-perl
    ports:
      - "80:80"
  api:
#    image: gcr.io/api-hubs/api-hubs:latest
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "9000:9000"
    volumes:
      - ./:/app
      - ../../../.ssh:/.ssh
    environment:
      - PYTHONUNBUFFERED=1

  mysql:
    image: mysql:8.0
    container_name: api_hubs_mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root_pass
      MYSQL_DATABASE: api_hubs_mysql
      MYSQL_USER: api_hubs
      MYSQL_PASSWORD: api_hubs_pass

  mongo:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: root